export { default as Button } from './button/Button'
export { default as ServiceItem } from './service-item/ServiceItem'
export { default as UserDataModal } from './modal/UserDataModal'
export { default as Background } from './background/Background'
export { default as BenefitsItem } from './benefits-item/BenefitsItem'
export { default as CTAText } from './text/CTAText.jsx'

export { default as Container } from './container/Container.js'
export { default as MainTitle } from './title/MainTitle.js'
export { default as MainText } from './text/MainText.js'
export { default as SiteLogo } from './logo/Logo.js'
